// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlo5WbikZ_k0qet1BX2XvgteLrOiCjWlY',
    appId: '1:413080049540:web:be7b4bc5b639d5bd62afd1',
    messagingSenderId: '413080049540',
    projectId: 'mynoteflutter',
    authDomain: 'mynoteflutter.firebaseapp.com',
    storageBucket: 'mynoteflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX03WCCyqss68Ub4ntyXjhpQvfQBpFX0A',
    appId: '1:413080049540:android:cce88c935dedf8dd62afd1',
    messagingSenderId: '413080049540',
    projectId: 'mynoteflutter',
    storageBucket: 'mynoteflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-h1oFDyuFqdW3N4xG15LKrYJTLl3RJ-U',
    appId: '1:413080049540:ios:9f96ca0e947aff9b62afd1',
    messagingSenderId: '413080049540',
    projectId: 'mynoteflutter',
    storageBucket: 'mynoteflutter.appspot.com',
    iosClientId: '413080049540-n4omitgj9b0crvh69bb2aekgl6li19t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-h1oFDyuFqdW3N4xG15LKrYJTLl3RJ-U',
    appId: '1:413080049540:ios:9f96ca0e947aff9b62afd1',
    messagingSenderId: '413080049540',
    projectId: 'mynoteflutter',
    storageBucket: 'mynoteflutter.appspot.com',
    iosClientId: '413080049540-n4omitgj9b0crvh69bb2aekgl6li19t3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
